import { ContexProvider } from "./context/context";
import Layout from "@/components/Layout";

import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ContexProvider>
          <Layout>{children}</Layout>
        </ContexProvider>
      </body>
    </html>
  );
}
