import type { Metadata } from "next";

import AppLayout from "./app.layout";
import "./globals.css";
import { ContexProvider } from "./context/context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ContexProvider>
          <AppLayout>{children}</AppLayout>
        </ContexProvider>
      </body>
    </html>
  );
}
