import type { Metadata } from "next";

import AppLayout from "./app.layout";
import "./globals.css";
import { ContexProvider } from "./context/context";
import QueryProvider from "./providers/QueryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>
          <ContexProvider>
            <AppLayout>{children}</AppLayout>
          </ContexProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
