export const RecipeActionTypes = {
  SET_RECIPES: "SET_RECIPES",
  ADD_RECIPE: "ADD_RECIPE",
  DELETE_RECIPE: "DELETE_RECIPE",
  RETRIEVE_RECIPE: "RETRIEVE_RECIPE",
  FILTER_RECIPES_BY_NAME: "FILTER_RECIPES_BY_NAME",
} as const;
